# Generated by Django 6.0.1 on 2026-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0012_elearning_users_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
