# Generated by Django 6.0.1 on 2026-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0013_course_duration_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.CharField(default='', max_length=50),
        ),
    ]
