# Generated by Django 6.0.1 on 2026-04-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0014_course_description_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
