# Generated by Django 6.0.1 on 2026-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0015_remove_teacher_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_assigned', models.CharField(default='', max_length=50)),
                ('teacherid', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
