# Generated by Django 6.0.1 on 2026-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0016_course_assign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_assign',
            new_name='courseassign',
        ),
    ]
