# Generated by Django 6.0.1 on 2026-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0005_rename_addcourse_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('file', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
