# Generated by Django 6.0.1 on 2026-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='headlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=50)),
                ('heading2', models.CharField(max_length=50)),
                ('heading3', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
