# Generated by Django 6.0.1 on 2026-04-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0007_headlines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headlines',
            old_name='image',
            new_name='file',
        ),
    ]
