# Generated by Django 6.0.1 on 2026-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0010_elearning_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearning_users',
            name='school_college',
            field=models.CharField(default='', max_length=100),
        ),
    ]
