# Generated by Django 6.0.1 on 2026-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0012_elearning_users_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_assigned', models.CharField(default='', max_length=50)),
                ('teacherid', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
