# Generated by Django 6.0.1 on 2026-05-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0013_courseassign_course_description_course_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='Description',
        ),
    ]
