# Generated by Django 6.0.1 on 2026-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0014_rename_description_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignedcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='', max_length=50)),
                ('teacher_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
