# Generated by Django 6.0.1 on 2026-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0015_assignedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourse',
            name='course_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assignedcourse',
            name='teacher_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
