# Generated by Django 6.0.1 on 2026-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0016_assignedcourse_course_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseassign',
        ),
    ]
