# Generated by Django 6.0.1 on 2026-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0017_delete_courseassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_assigned', models.CharField(default='', max_length=50)),
                ('teacherid', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='my_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default=' ', max_length=50)),
                ('course_name', models.CharField(default=' ', max_length=50)),
                ('user_name', models.CharField(default=' ', max_length=50)),
                ('course_date', models.DateField(default=' ', max_length=50)),
                ('expiry_date', models.DateField(default=' ', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='assignedcourse',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
    ]
