# Generated by Django 6.0.1 on 2026-08-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0018_courseassign_my_batch_delete_assignedcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_batch',
            name='course_date',
        ),
        migrations.RemoveField(
            model_name='my_batch',
            name='expiry_date',
        ),
    ]
