# Generated by Django 6.0.1 on 2026-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0019_remove_my_batch_course_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_batch',
            name='course_taken_date',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
