# Generated by Django 6.0.1 on 2026-08-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0020_my_batch_course_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_batch',
            name='course_taken_date',
            field=models.DateField(default=' ', max_length=50),
        ),
    ]
