# Generated by Django 6.0.1 on 2026-08-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0021_alter_my_batch_course_taken_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_batch',
            old_name='course_name',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='my_batch',
            name='user_name',
        ),
    ]
