# Generated by Django 6.0.1 on 2026-08-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0022_rename_course_name_my_batch_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_batch',
            name='user_email',
            field=models.EmailField(default=' ', max_length=50),
        ),
    ]
