# Generated by Django 6.0.1 on 2026-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0023_alter_my_batch_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearning_users',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
