# Generated by Django 6.0.1 on 2026-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0024_elearning_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearning_users',
            name='img',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
