# Generated by Django 6.0.1 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0025_elearning_users_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearning_users',
            name='id',
        ),
        migrations.AlterField(
            model_name='elearning_users',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
