# Generated by Django 6.0.1 on 2026-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0026_remove_elearning_users_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearning_users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elearning_users',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
