# Generated by Django 6.0.1 on 2026-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0027_elearning_users_id_alter_elearning_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_batch',
            name='status',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
