# Generated by Django 6.0.1 on 2026-08-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0028_my_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default=' ', max_length=50)),
                ('lecture_title', models.CharField(default=' ', max_length=50)),
                ('lecture_file', models.FileField(default=' ', upload_to='lecture')),
                ('teacher_email', models.EmailField(default=' ', max_length=50)),
            ],
        ),
    ]
