# Generated by Django 6.0.1 on 2026-09-07 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0030_liveclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearningapp.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearningapp.elearning_users')),
            ],
        ),
    ]
