# Generated by Django 6.0.1 on 2026-09-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearningapp', '0031_liveattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveAttendance',
        ),
    ]
